[dependencies]
arrow-schema = {workspace = true}
arrow-flight = {workspace = true}
arrow-ipc = {workspace = true}
async-channel = "2.5.0"
async-trait = {workspace = true}
bytes = {workspace = true}
celeborn-client = {git = "ssh://git@gitlab.alibaba-inc.com/dtlake_group/celeborn.git", branch = "standalone_and_rust", optional = true}
common-error = {path = "../common/error", default-features = false}
common-runtime = {path = "../common/runtime", default-features = false}
daft-core = {path = "../daft-core", default-features = false}
daft-io = {path = "../daft-io", default-features = false}
daft-micropartition = {path = "../daft-micropartition", default-features = false}
daft-recordbatch = {path = "../daft-recordbatch", default-features = false}
daft-schema = {path = "../daft-schema", default-features = false}
daft-writers = {path = "../daft-writers", default-features = false}
futures = {workspace = true}
tokio = {workspace = true, features = ["fs", "io-util"]}
tonic = {workspace = true}

[features]
celeborn = ["dep:celeborn-client"]

[lints]
workspace = true

[package]
name = "daft-shuffles"
edition.workspace = true
version.workspace = true
